# PYTHON PROGRAMMING FUNDAMENTALS - PART B


This Notebook will cover the following topics:    
- Numpy basics
- Built-in methods and functions 
- Obtain shape, length and type of Numpy arrays
- Reshape 
- Minimum and maximum and their indices
- Mathematical Operations
- Indexing and slicing 
- Selection 



# NUMPY BASICS
- NumPy is a Linear Algebra Library used for multidimensional arrays
- Installation: Use the command window, type: conda install numpy

In [ ]:


[3,4,5,3,2] # 1d



In [3]:
import numpy as np 


In [12]:
# One-dimensional array 
my_list = [5, 3, 10,1.3, True,2+4j,"dev"]
my_list

[5, 3, 10, 1.3, True, (2+4j), 'dev']

In [15]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [13]:
y = np.array(my_list)

In [14]:
y

array(['5', '3', '10', '1.3', 'True', '(2+4j)', 'dev'], dtype='<U64')

In [16]:
type(y)

numpy.ndarray

In [17]:
# multi-dimensional (Matrix definition) 
matrix = np.array([[1, 2,3], [3, 4,3], [3, 4,3]]) # ([[1,3],    [3,4],     [1,3]])

In [18]:
matrix

array([[1, 2, 3],
       [3, 4, 3],
       [3, 4, 3]])

# BUILT-IN METHODS AND FUNCTIONS

In [29]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(10)
x

array([0.88599365, 0.24236817, 0.96344705, 0.36691055, 0.36807441,
       0.16775364, 0.69295767, 0.4868352 , 0.60501982, 0.43991195])

In [39]:
x = np.random.rand(10,4)
x

array([[0.42392013, 0.70956205, 0.61344414, 0.51788854],
       [0.1333331 , 0.85777734, 0.49096581, 0.39211391],
       [0.79313275, 0.62274905, 0.09676178, 0.31902586],
       [0.65627928, 0.60605881, 0.46025068, 0.11606342],
       [0.62152799, 0.26976444, 0.033387  , 0.99398852],
       [0.8776032 , 0.17489384, 0.97582675, 0.51794942],
       [0.92290581, 0.6373684 , 0.29175939, 0.4596428 ],
       [0.69079789, 0.23451416, 0.97089098, 0.36329218],
       [0.13662828, 0.60077493, 0.19985402, 0.79400106],
       [0.04898736, 0.6647563 , 0.89746748, 0.81958417]])

In [116]:
# "randn()" normal distribution between 1 and 
x = np.random.randn(3,3)
x

array([[-0.02598338, -1.77671867,  0.43908895],
       [-0.00853011, -1.41116295, -1.12199741],
       [ 1.0103498 ,  0.60817858,  0.09827657]])

In [68]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

8

In [79]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 100, 15)
x

array([19, 53, 15, 85, 44, 35, 70, 67, 40, 94, 17, 84, 46, 81,  9])

In [81]:
x = np.arange(1, 50, dtype=int)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [115]:
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [85]:
x = np.eye(10, dtype=int)
x

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [90]:
# Array of ones
x = np.ones((3,3) , dtype=int)
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [99]:
# Matrices of ones
x = np.ones((3,3,3),dtype=float)
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [95]:
x.shape

(3, 3, 3)

In [92]:
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

In [96]:
y

array(['5', '3', '10', '1.3', 'True', '(2+4j)', 'dev'], dtype='<U64')

In [97]:
# get Length 
len(y)

7

In [100]:
# get shape
x.shape

(3, 3, 3)

In [101]:
matrix

array([[1, 2, 3],
       [3, 4, 3],
       [3, 4, 3]])

In [102]:
matrix.shape

(3, 3)

In [103]:
matrix.dtype

dtype('int32')

# RESHAPE

In [104]:
y = np.array([3, 5, 7, 8,4,4,4,6,2,3])
y.shape

(10,)

In [112]:
y = y.reshape(10,1)

In [113]:
y.shape

(10, 1)

In [114]:
y

array([[3],
       [5],
       [7],
       [8],
       [4],
       [4],
       [4],
       [6],
       [2],
       [3]])

# MAX AND MIN VALUES AND THEIR INDEX

In [117]:
# "randn()" normal distribution between 1 and 
x = np.random.randn(3,3)
x

array([[ 0.19763155,  1.06053125,  0.82888243],
       [-0.75179466,  0.31768182,  1.62533728],
       [-0.51369214, -1.38823335,  0.36021738]])

In [125]:
a = [2,34,6]
min(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [120]:
x.max()

1.6253372813755824

In [121]:
x.min()

-1.388233352995259

In [122]:
# Obtain the index of the max value
y.argmax()

3

In [123]:
# Obtain the index of the min value
y.argmin()

8

# MATHEMATICAL OPERATIONS

In [126]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [127]:
y = np.arange(1, 5)
z = x+y
z

array([2, 4, 6, 8])

In [128]:
z = x**2
z

array([ 1,  4,  9, 16], dtype=int32)

In [132]:
k = np.sqrt(z)
k

array([1.64872127, 2.71828183, 4.48168907, 7.3890561 ])

In [131]:
import math

a = math.sqrt(z)

TypeError: only size-1 arrays can be converted to Python scalars

In [130]:
z = np.exp(y)
z

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# ELEMENTS SLICING AND INDEXING

In [2]:
import numpy as np

In [3]:
x = np.random.randint(1,11, 10)
x

array([ 6,  7,  8,  6, 10,  4, 10,  5, 10,  7])

In [4]:
x[3]

6

In [5]:
x[0:3]

array([6, 7, 8])

In [ ]:
# Broadcasting, altering several values in a numpy array at once
x[0:6] = 10
x

In [6]:
matrix = np.random.randint(1,10, (5, 5), dtype=int)
matrix

array([[5, 1, 8, 4, 7],
       [3, 1, 4, 8, 6],
       [2, 4, 7, 1, 5],
       [3, 8, 4, 9, 3],
       [2, 4, 7, 7, 2]])

In [ ]:
# MAT[ START_ROW:STOP_ROW  ,  START_COL:STOP_COL]

In [7]:
# Get a row from a mtrix
matrix[2] 

array([2, 4, 7, 1, 5])

In [8]:
# Get element
matrix[0][2]

8

In [9]:
mini_matrix = matrix[:3]
mini_matrix

array([[5, 1, 8, 4, 7],
       [3, 1, 4, 8, 6],
       [2, 4, 7, 1, 5]])

In [ ]:
mini_matrix = matrix[2:]
mini_matrix

In [14]:
mini_matrix = matrix[0:, :2]
mini_matrix

array([[5, 1],
       [3, 1],
       [2, 4],
       [3, 8],
       [2, 4]])

In [11]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[8, 4, 7],
       [4, 8, 6],
       [7, 1, 5],
       [4, 9, 3],
       [7, 7, 2]])

# ELEMENTS SELECTION

In [15]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[9, 8, 9, 6, 4],
       [2, 5, 2, 3, 5],
       [6, 1, 6, 7, 3],
       [2, 1, 1, 8, 2],
       [4, 4, 9, 9, 2]])

In [16]:
matrix>3

array([[ True,  True,  True,  True,  True],
       [False,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [False, False, False,  True, False],
       [ True,  True,  True,  True, False]])

In [17]:
new_matrix = matrix[matrix>3]
new_matrix

array([9, 8, 9, 6, 4, 5, 5, 6, 6, 7, 8, 4, 4, 9, 9])

In [18]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([8, 6, 4, 2, 2, 6, 6, 2, 8, 2, 4, 4, 2])

In [21]:
524%2 == 0

True